{
    "name": "Booking Order Gabe Siringoringo 19 Maret 2024",
    "summary": "Hashmicro Odoo Developer Test - Booking Order Gabe Siringoringo 19 Maret 2024",
    "author": "Gabe Siringoringo",
    "maintainers": ["gaberingo"],
    "website": "https://github.com/gaberingo",
    "category": "Custom",
    "version": "17.0.1.1.0",
    "depends": ["sale","sale_management"],
    "data": [
        'security/ir.model.access.csv',
        'data/work_order_data.xml',
        'report/report_templates.xml',
        'report/report.xml',
        'views/cancelled_confirm.xml',
        'views/service_team_view.xml',
        'views/booking_order_view.xml',
        'views/sale_order_views_inherit.xml',
        'views/work_order_view.xml',
        'views/sale_menus_inherit.xml',
    ],
    "installable": True,
    "license": "OPL-1",
    "module_type": "official",
}